export const CheckBox = {
  id: 6,
  name: "CheckBox1",
  type: "CheckBox",
  caption: "CheckBox1",
  controlSource: "",
  alignment:"0 - fmAlignmentLeft",
  controlTipText: "",
  enabled: true,
  groupName: "",
  helpContextId: 0,
  locked: false,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "7 - fmPicturePositionAboveCenter",
  tabindex: 9,
  tabStop: true,
  tag: "",
  tripleState: false,
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    // zIndex: "1",
    //  backgroundColor: "white",
    //  borderColor: "#eeeeee",
    //  border: "1px solid",
    //  borderStyle: "solid",
    //  fontFamily: "Arial, Helvetica, sans-serif",
    //  color: "black",
    //  textAlign: "left",
    //  cursor: "default",
    //  boxShadow: "none",
    // wordWrap: "break-word",
    // overflow: "hidden",
    // whiteSpace: "normal",
    paddingLeft:'10px'
  },
};
