export const ComboBox = {
  id: 4,
  name: "ComboBox1",
  type: "ComboBox",
  autoSize: false,
  autoTab: false,
  autoWordSelect: true,
  boundColumn: 1,
  columnCount: 1,
  columnHeads: false,
  columnWidths: "",
  controlSource: "",
  controlTipText: "",
  dragBehaviour: "0 - fmDragBehaviotDisabled",
  // dropButtonStyle: "1 - fmDropButtonStyleArrow",
  enabled: true,
  enterFieldBehaviour: "0 - fmEnterFiledBehaviorSelectAll",
  helpContextId: 0,
  hideSelection: true,
  imeMode: "0 - fmIMEModeNOControl",
  listRows: 8,
  // listStyle: "0 - fmListStylePlain",
  listStyle: "1 - fmListStyleOption",
  listWidth: "100 pt",
  locked: false,
  matchEntry: "1 - fmMatchEntryComplete",
  matchRequired: false,
  maxLength: 0,
  mouseIcon: "(None)",
  rowSource: "",
  selectionMargin: true,
  showDropButtonWhen: "block",
  tabindex: 4,
  tabStop: true,
  tag: "",
  text: "",
  textColumn: -1,
  topIndex: -1,
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "100px",
    backgroundImage:"none",
    // zIndex: "1",
    // backgroundColor: "white",
    // borderColor: "#eeeeee",
    // border: "1px solid",
    // borderStyle: "solid",
    // fontFamily: "Arial, Helvetica, sans-serif",
    // color: "black",
    // textAlign: "left",
    // cursor: "default",
    // boxShadow: "none",
    // wordWrap: "break-word",
    // overflow: "hidden",
    // whiteSpace: "normal",
    // paddingLeft:"10px",
  },
};
