export const CommandButton = {
  id: 2,
  name: "CommandButton1",
  type: "CommandButton",
  accelerator: "",
  autoSize: false,
  caption: "CommandButton1",
  title: "",
  enabled: true,
  helpContextId: 0,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "0 - fmPicturePositionLeftTop",
  tabindex: 1,
  tabStop: false,
  tag: "",
  takeFocusOnClick: true,
  lock: false,
  visible: true,
  wordWrap: true,
  isActive:false,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    borderColor: "#eeeeee",
    border: "1px solid",
    borderStyle: "solid",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
    textAlign: "left",
    cursor: "default",
    boxShadow: "none",
    wordWrap: "break-word",
    overflow: "hidden",
    whiteSpace: "normal",
  },
};
