export const Frame = {
  id: 9,
  name: "Frame1",
  type: "Frame",
  caption: "Frame1",
  controlTipText: "",
  cycle: "0 - fmCycleAllForms",
  enabled: true,
  helpContextId: 0,
  keepScrollsBarsVisible: "3 - fmScrollBarsBoth",
  mouseIcon: "(None)",
  picture: "(None)",
  pictureAlignment: "2 - fmPictureAlignmentCenter",
  pictureSizeMode: "0 - fmPictureSizeModeClip",
  pictureTiling: false,
  scrollBars: "0 - fmScrollBarsNone",
  scrollHeight: 0,
  scrollLeft: 0,
  scrollTop: 0,
  scrollWidth: 0,
  tabindex: 11,
  tabStop: true,
  tag: "",
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    borderColor: "#eeeeee",
    border: "1px solid",
    borderStyle: "solid",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
    textAlign: "left",
    cursor: "default",
    boxShadow: "none",
    wordWrap: "break-word",
    overflow: "hidden",
    whiteSpace: "normal",
  },
};
