export const Image = {
  id: 14,
  name: "Image1",
  type: "Image",
  controlTipText: "",
  enabled: true,
  mouseIcon: "(None)",
  picture: "(None)",
  pictureAlignment: "2 - fmPictureAlignmentCenter",
  pictureSizeMode: "0 - fmPictureSizeModeClip",
  pictureTiling: false,
  tag: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    borderColor: "#eeeeee",
    border: "1px solid",
    borderStyle: "solid",
    color: "black",
    textAlign: "left",
    cursor: "default",
    boxShadow: "none",
  },
};
