export const Label = {
  id: 1,
  name: "Label1",
  type: "Label",
  accelerator: "",
  isActiveAccelerator:"",
  autoSize: false,
  caption: "Label1",
  title: "Label1",
  enabled: true,
  helpContextId: 0,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "7 - fmPicturePositionAboveCenter",
  tabindex: 0,
  tabStop: false,
  tag: "",
  visible: true,
  wordWrap: true,
  isActive:false,
  style: {
    left: "70px",
    top: "0px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    border: "none",
    backgroundColor: "white",
    borderColor: "ghostwhite",
    fontFamily: "Tahoma",
    color: "black",
    textAlign: "left",
    backgroundImage:"",
    backgroundPosition:"",
    backgroundPositionX:"",
    backgroundPositionY:"",
    backgroundRepeat:"",
    cursor: "default",
    boxShadow: "none",
    wordWrap: "break-word",
    overflow: "hidden",
    whiteSpace: "normal",
    overflowWrap:"normal"
  },
};
