export const ListBox = {
  id: 5,
  name: "ListBox1",
  type: "ListBox",
  boundColumn: 1,
  columnCount: 1,
  columnHeads: false,
  columnWidths: "",
  controlSource: "",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  imeMode: "0 - fmIMEModeNOControl",
  integralHeight: true,
  listStyle: "0 - fmListStylePlain",
  locked: false,
  matchEntry: "0 - fmMatchEntryFirstLetter",
  mouseIcon: "(None)",
  multiSelect: "0 - fm-MousePointerDefault",
  rowSource: "",
  tabindex: 6,
  tabStop: true,
  tag: "",
  text: "",
  textColumn: -1,
  topIndex: -1,
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    borderColor: "#eeeeee",
    border: "1px solid",
    borderStyle: "solid",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
    textAlign: "left",
    cursor: "default",
    boxShadow: "none",
    wordWrap: "break-word",
    overflow: "hidden",
    whiteSpace: "normal",
    paddingLeft:"0px"
  },
};
