export const MultiPage = {
  id: 11,
  name: "MultiPage1",
  type: "MultiPage",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  multiRow: false,
  tabFixedHeight: 0,
  tabFixedWidth: 0,
  tabindex: 13,
  tabOrientation: "0 - fmTabOrientationTop",
  tabStop: true,
  tag: "",
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
  },
};
