export const RefEdit = {
  id: 3,
  name: "RefEdit1",
  type: "RefEdit",
  autoSize: false,
  autoTab: false,
  autoWordSelect: true,
  controlSource: "",
  controlTipText: "",
  dragBehaviour: "0 - fmDragBehaviotDisabled",
  enabled: true,
  enterFieldBehaviour: "0 - fmEnterFiledBehaviorSelectAll",
  enterKeyBehaviour: false,
  helpContextId: 0,
  hideSelection: true,
  integralHeight: true,
  imeMode: "0 - fmIMEModeNoControl",
  locked: false,
  maxLength: 0,
  mouseIcon: "(None)",
  multiLine: false,
  passwordChar: "",
  scrollBars: "1 - fmScrollBarsNone",
  selectionMargin: true,
  tabindex: 4,
  tabKeyBehaviour: false,
  tabStop: false,
  tag: "",
  text: "",
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    borderColor: "#eeeeee",
    border: "1px solid",
    borderStyle: "solid",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
    textAlign: "left",
    cursor: "default",
    boxShadow: "none",
    wordWrap: "break-word",
    overflow: "hidden",
    whiteSpace: "normal",
  },
};
