export const SpinButton = {
  id: 13,
  name: "SpinButton1",
  type: "SpinButton",
  controlSource: "",
  controlTipText: "",
  delay: 50,
  enabled: true,
  helpContextId: 0,
  max: 100,
  min: 0,
  mouseIcon: "(None)",
  orientation: "-1 - fmOrientationAuto",
  smallChange: 1,
  tabindex: 13,
  tabStop: true,
  tag: "",
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
  },
};
