export const TabStrip = {
  id: 10,
  name: "TabStrip1",
  type: "TabStrip",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  mouseIcon: "(None)",
  multiRow: false,
  picture: "(None)",
  tabFixedHeight: 0,
  tabFixedWidth: 0,
  tabindex: 13,
  tabOrientation: "0 - fmTabOrientationTop",
  tabStop: true,
  tag: "",
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
    cursor: "default",
  },
};
