export const TextBox = {
  id: 3,
  name: "TextBox1",
  type: "TextBox",
  autoSize: false,
  autoTab: false,
  autoWordSelect: true,
  cursorStartPosition:0,
  cursorEndPosition:0,
  controlSource: "",
  controlTipText: "",
  dragBehavior: "0 - fmDragBehaviorDisabled",
  enabled: true,
  enterFieldBehavior: "0 - fmEnterFiledBehaviorSelectAll",
  enterKeyBehavior: false,
  helpContextId: 0,
  hideSelection: true,
  integralHeight: true,
  imeMode: "0 - fmIMEModeNOControl",
  locked: false,
  maxLength: "",
  mouseIcon: "(None)",
  multiLine: false,
  passwordChar: "",
  scrollBars: "1 - fmScrollBarsHorizontal",
  selectionMargin: true,
  tabindex: 4,
  tabKeyBehaviour: false,
  tabStop: false,
  tag: "",
  text: "",
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    borderColor: "#eeeeee",
    border: "1px solid",
    borderStyle: "solid",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
    textAlign: "left",
    cursor: "default",
    boxShadow: "none",
    overflow: "hidden",
    whiteSpace: "none",
    paddingLeft:"10px",
  },
};
