export const ToggleButton = {
  id: 8,
  name: "ToggleButton1",
  type: "ToggleButton",
  caption: "ToggleButton1",
  accelerator: "",
  autoSize: false,
  controlSource: "",
  controlTipText: "",
  enabled: true,
  helpContextId: 0,
  locked: false,
  mouseIcon: "(None)",
  picture: "(None)",
  picturePosition: "7 - fmPicturePositionAboveCenter",
  tabindex: 11,
  tabStop: true,
  tripleState: false,
  tag: "",
  value: "",
  visible: true,
  style: {
    left: "20px",
    top: "100px",
    width: "100px",
    height: "40px",
    zIndex: "1",
    backgroundColor: "white",
    borderColor: "#eeeeee",
    border: "1px solid",
    borderStyle: "solid",
    fontFamily: "Arial, Helvetica, sans-serif",
    color: "black",
    textAlign: "left",
    cursor: "default",
    boxShadow: "none",
    wordWrap: "break-word",
    overflow: "hidden",
    whiteSpace: "normal",
  },
};
