export const treeData = {
  name: "VBA Project(Book1)",
  userForms: [
    {
      name: "Forms",
      userForms: [
        {
          id: 1,
          controlZIndex: 3,
          name: "UserForm1",
          type: "UserForm",
          visible: true,
          autoSize: false,
          caption: "UserForm1",
          cycle: "0 - fmCycleAllForms",
          drawBuffer: 32000,
          enabled: true,
          helpContextId: 0,
          keepScrollsBarsVisible: "3 - fmScrollBarsBoth",
          mouseIcon: "(None)",
          picture: "(None)",
          pictureAlignment: "0 - fmPictureAlignmentTopLeft",
          pictureSizeMode: "0 - fmPictureSizeModeClip",
          pictureTiling: false,
          rightToLeft: false,
          scrollBars: "0 - fmScrollBarsNone",
          scrollHeight: 0,
          scrollLeft: 0,
          scrollTop: 0,
          startUpPosition: "0 - Manual",
          scrollWidth: 0,
          showModal: true,
          tag: "",
          whatsThisButton: false,
          whatsThisHelp: false,
          controls: [
            {
            id: 1,
            name: "Label1",
            type: "Label",
            accelerator: "a",
            autoSize: false,
            caption: "Label1",
           isActiveAccelerator:"La&#818;bel1", 
            title: "Label1",
            enabled: true,
            helpContextId: 0,
            mouseIcon: "(None)",
            picture: "(None)",
            picturePosition: "0 - fmPicturePositionLeftTop",
            tabindex: 0,
            tabStop: false,
            tag: "",
            visible: true,
            wordWrap: true,
            style: {
              left: "70px",
              top: "0px",
              width: "100px",
              height: "40px",
              zIndex: "1",
              border: "none",
              backgroundColor: "white",
              borderColor: "ghostwhite",
              fontFamily: "Tahoma",
              color: "black",
              textAlign: "left",
              cursor: "default",
              boxShadow: "none",
              wordWrap: "break-word",
              backgroundImage:"",
              whiteSpace: "normal",
              paddingLeft:"0px"
            }
            }],
          outerWindowStyle: {
            container: {
              position: "absolute",
              textAlign: "left",
              border: "3px solid rgb(159, 196, 224)",
              width: "700px",
              height: "400px",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              backgroundColor: "white",
              display: "block",
              zIndex: "2",
              top: "50px",
              left: "50px",
              resize: "both",
              minHeight: "300px",
              minWidth: "500px",
            },
            top: {
              padding: "8px",
              background:
                "linear-gradient(30deg, rgb(195, 220, 236) 0%, rgb(152, 192, 215) 50%, rgb(137, 193, 226) 51%, rgba(161, 189, 210, 0.56) 100%)",
              height: "21px",
            },
            closeButton: {
              right: "10px",
              position: "absolute",
              backgroundColor: "red",
              width: "24px",
            },
          },
          innerWindowStyle: {
            container: {
              position: "relative",
              textAlign: "left",
              border: "none",
              width: "400px",
              height: "250px",
              resize: "both",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              maxWidth: "98%",
              maxHeight: "88%",
              margin: "4px",
              backgroundColor: "white",
              borderColor: "ghostwhite",
              fontFamily: "Tahoma",
              color: "black",
              left: "0",
              top: "0",
              zoom: "100%",
              cursor: "text",
              boxShadow: "none",
            },
            top: {
              padding: "8px",
              background:
                "linear-gradient(30deg, rgb(195, 220, 236) 0%, rgb(152, 192, 215) 50%, rgb(137, 193, 226) 51%, rgba(161, 189, 210, 0.56) 100%)",
              height: "21px",
            },
            innerContainer: {
              // cursor: "crosshair",
              width: "100%",
              height: "calc(100% - 37px)",
              backgroundColor: "#e3e3e357",
              position: "absolute",
              left: "0px",
              top: "35px",
              backgroundPositionX:"center",
              backgroundRepeat:"repeat",
              backgroundPositionY:"center",
              backgroundImage:"radial-gradient(circle, rgb(0, 0, 0) 0.5px, rgba(0, 0, 0, 0) 0.2px)",
              backgroundSize: " 9px 10px",
              overflowX:"",
              overflowY:"",
              zoom: "100%",
            },
            closeButton: {
              right: "10px",
              position: "absolute",
              backgroundColor: "red",
              width: "24px",
            },
            whatsThisButton: {
              right: "35px",
              top: "11px",
              position: "absolute",
              borderStyle: "none",
              color: "white",
              backgroundColor: "#9fb0cb",
            },
          },
        },
      ],
    },
  ],
};
